/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ghostTipsFhevmSol from "./GhostTipsFHEVM.sol";
export type { ghostTipsFhevmSol };
export type { FHECounter } from "./FHECounter";
export type { GhostTips } from "./GhostTips";
export type { GhostTipsSimple } from "./GhostTipsSimple";
export type { GhostToken } from "./GhostToken";
