/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGhostToken,
  IGhostTokenInterface,
} from "../../../contracts/GhostTipsFHEVM.sol/IGhostToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "amount",
        type: "uint64",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGhostToken__factory {
  static readonly abi = _abi;
  static createInterface(): IGhostTokenInterface {
    return new Interface(_abi) as IGhostTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGhostToken {
    return new Contract(address, _abi, runner) as unknown as IGhostToken;
  }
}
