/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GhostTipsFHEVM__factory } from "./GhostTipsFHEVM__factory";
export { IGhostToken__factory } from "./IGhostToken__factory";
