/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GhostTipsSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createTipJar"
      | "deactivateTipJar"
      | "getTipJarCount"
      | "getUserTipJars"
      | "owner"
      | "renounceOwnership"
      | "sendTip"
      | "tipCount"
      | "tipJarCount"
      | "tipJars"
      | "tips"
      | "transferOwnership"
      | "userTipJars"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "TipJarCreated"
      | "TipReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createTipJar",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTipJar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTipJarCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTipJars",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendTip",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "tipCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tipJarCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tipJars",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tips", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTipJars",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createTipJar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTipJar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTipJarCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTipJars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendTip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tipCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tipJarCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tipJars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tips", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTipJars",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipJarCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    title: string
  ];
  export type OutputTuple = [id: bigint, creator: string, title: string];
  export interface OutputObject {
    id: bigint;
    creator: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipReceivedEvent {
  export type InputTuple = [
    tipJarId: BigNumberish,
    amount: BigNumberish,
    tipId: BigNumberish
  ];
  export type OutputTuple = [tipJarId: bigint, amount: bigint, tipId: bigint];
  export interface OutputObject {
    tipJarId: bigint;
    amount: bigint;
    tipId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GhostTipsSimple extends BaseContract {
  connect(runner?: ContractRunner | null): GhostTipsSimple;
  waitForDeployment(): Promise<this>;

  interface: GhostTipsSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTipJar: TypedContractMethod<
    [_title: string, _description: string, _category: string],
    [bigint],
    "nonpayable"
  >;

  deactivateTipJar: TypedContractMethod<
    [_tipJarId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTipJarCount: TypedContractMethod<[], [bigint], "view">;

  getUserTipJars: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendTip: TypedContractMethod<
    [_tipJarId: BigNumberish, _message: string],
    [void],
    "payable"
  >;

  tipCount: TypedContractMethod<[], [bigint], "view">;

  tipJarCount: TypedContractMethod<[], [bigint], "view">;

  tipJars: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        title: string;
        description: string;
        category: string;
        totalReceived: bigint;
        tipCount: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  tips: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        tipJarId: bigint;
        amount: bigint;
        timestamp: bigint;
        message: string;
        isAnonymous: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userTipJars: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTipJar"
  ): TypedContractMethod<
    [_title: string, _description: string, _category: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateTipJar"
  ): TypedContractMethod<[_tipJarId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTipJarCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTipJars"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendTip"
  ): TypedContractMethod<
    [_tipJarId: BigNumberish, _message: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "tipCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tipJarCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tipJars"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        title: string;
        description: string;
        category: string;
        totalReceived: bigint;
        tipCount: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tips"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, boolean] & {
        tipJarId: bigint;
        amount: bigint;
        timestamp: bigint;
        message: string;
        isAnonymous: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userTipJars"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TipJarCreated"
  ): TypedContractEvent<
    TipJarCreatedEvent.InputTuple,
    TipJarCreatedEvent.OutputTuple,
    TipJarCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TipReceived"
  ): TypedContractEvent<
    TipReceivedEvent.InputTuple,
    TipReceivedEvent.OutputTuple,
    TipReceivedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TipJarCreated(uint256,address,string)": TypedContractEvent<
      TipJarCreatedEvent.InputTuple,
      TipJarCreatedEvent.OutputTuple,
      TipJarCreatedEvent.OutputObject
    >;
    TipJarCreated: TypedContractEvent<
      TipJarCreatedEvent.InputTuple,
      TipJarCreatedEvent.OutputTuple,
      TipJarCreatedEvent.OutputObject
    >;

    "TipReceived(uint256,uint256,uint256)": TypedContractEvent<
      TipReceivedEvent.InputTuple,
      TipReceivedEvent.OutputTuple,
      TipReceivedEvent.OutputObject
    >;
    TipReceived: TypedContractEvent<
      TipReceivedEvent.InputTuple,
      TipReceivedEvent.OutputTuple,
      TipReceivedEvent.OutputObject
    >;
  };
}
