/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FHECounter } from "./FHECounter";
export type { GhostTips } from "./GhostTips";
export type { GhostTipsSimple } from "./GhostTipsSimple";
